### ISSUE TITLE
Checkpoint for Kinetics400

### ISSUE THREAD

**Issue by Wangbk-dl** [daniel-code/TubeViT#17]
Excellent work. I'm wondering if you could provide the checkpoints for Kinetics dataset?

**Comment by daniel-code** [comment]
Sorry, I didn't have the checkpoint for Kinetics.
The dataset was too large that my laptop couldn't train on it.
You can fork my code and train on Kinetics.

**Comment by babyta** [comment]
Is this the official code?

**Comment by daniel-code** [comment]
This is an unofficial implementation. It is based on the paper but still has many ways different than the paper.

**Comment by babyta** [comment]
> @babyta This is an unofficial implementation. It is based on the paper but still has many ways different than the paper.

thank you for your reply
