### ISSUE TITLE
how to load the pretrained parameters from vit

### ISSUE THREAD

**Issue by kt-ck** [daniel-code/TubeViT#20]
i try two ways , but they not work well .
(i) when  i change the encoder block with ViTModel from huggingface
```
    pretrained_vit = ViTModel.from_pretrained("pretrained_model/")
    self.encoder = pretrained_vit.encoder
```
  however, i got this error. _TypeError: linear(): argument 'input' (position 1) must be Tensor, not BaseModelOutput_, it raised by self.attention_pooling
(ii) i try to set parameters directly 
```
pretrained_dict = ...
model_dict = model.state_dict()

# 1. filter out unnecessary keys
pretrained_dict = {k: v for k, v in pretrained_dict.items() if k in model_dict}
# 2. overwrite entries in the existing state dict
model_dict.update(pretrained_dict) 
# 3. load the new state dict
model.load_state_dict(pretrained_dict) 
```
however, there are no same key name

**Comment by daniel-code** [comment]
Dear @kt-ck,

In your first approach, you should also modify `forward` function since huggingface VIT encoder return `BaseModelOutput` object, not the `torch.Tensor`.

```python
class TubeViT(nn.Module):
    def __init__(...):
        ...
        pretrained_vit = ViTModel.from_pretrained("pretrained_model/")
        self.encoder = pretrained_vit.encoder

    def forward(self, x):
        ...
        # Attention pooling
        x = self.attention_pooling(x.last_hidden_state)
```
After changing the encoder, you can follow the `convert_vit_weight.py` to convert the 2D-CNN embedding weight to Tube embedding weight.

**Comment by kt-ck** [comment]
thanks
