### ISSUE TITLE
test script

### ISSUE THREAD

**Issue by linpennnnggg** [daniel-code/TubeViT#22]
Could you make the test script public

**Comment by daniel-code** [comment]
Dear @linpennnnggg,

I'm sorry for not getting back to you sooner. Did you mean the test script for one video clip, or the test processing the same as the paper?

**Comment by linpennnnggg** [comment]
yeah,I mean the the test script for one video clip.could you provide? If possible, I would be extremely grateful！

**Comment by daniel-code** [comment]
Unfortunately, I have not implemented the test script yet.

Welcome to contribute to it. 💪🏻
