### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by 123456ZF** [daniel-code/TubeViT#23]
Can you publish your dataset?

**Comment by daniel-code** [comment]
Dear @123456ZF,

The dataset can be downloaded from [here](https://www.crcv.ucf.edu/data/UCF101.php).

I modified the [torchvision.datasets.UCF101](https://pytorch.org/vision/stable/generated/torchvision.datasets.UCF101.html#torchvision.datasets.UCF101) for this repository.

**Comment by 123456ZF** [comment]
@daniel-code Thank you
